# Generated by Django 5.0.8 on 2025-09-09 04:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador/Docente'), ('student', 'Estudiante')], default='student', max_length=10, verbose_name='Rol')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('whatsapp_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp')),
                ('document_number', models.CharField(blank=True, max_length=20, verbose_name='Número de documento')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso por Protección Temporal'), ('NIT', 'NIT'), ('OTRO', 'Otro')], default='CC', max_length=10, verbose_name='Tipo de documento')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultorioJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nua', models.CharField(max_length=20, unique=True, verbose_name='Número Único de Asesoría (NUA)')),
                ('consultation_date', models.DateField(verbose_name='Fecha de asesoría')),
                ('consultation_area', models.CharField(choices=[('civil', 'Civil'), ('publico', 'Público'), ('laboral', 'Laboral'), ('penal', 'Penal'), ('comercial', 'Comercial'), ('familia', 'Familia'), ('otro', 'Otro')], max_length=20, verbose_name='Área de consulta')),
                ('consultation_area_other', models.CharField(blank=True, max_length=100, verbose_name='Otra área (especificar)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de revisión'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Docente asignado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Caso Consultorio Jurídico',
                'verbose_name_plural': 'Casos Consultorio Jurídico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnexoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anexo', models.CharField(max_length=200, verbose_name='Nombre del anexo')),
                ('archivo', models.FileField(upload_to='anexos/%Y/%m/', verbose_name='Archivo')),
                ('numero_folios', models.PositiveIntegerField(default=1, verbose_name='Número de folios')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Anexo Usuario',
                'verbose_name_plural': 'Anexos Usuario',
            },
        ),
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('empleado', 'Empleado/a'), ('pensionado', 'Pensionado/a'), ('independiente', 'Independiente')], max_length=15, verbose_name='Tipo de actividad')),
                ('employer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del empleador')),
                ('pension_fund', models.CharField(blank=True, max_length=100, verbose_name='Fondo de pensión')),
                ('independent_activity', models.TextField(blank=True, verbose_name='Tipo de actividad independiente')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_economica', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Actividad Económica',
                'verbose_name_plural': 'Actividades Económicas',
            },
        ),
        migrations.CreateModel(
            name='Contraparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombres y apellidos/Denominación')),
                ('document_type', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso por Protección Temporal'), ('NIT', 'NIT'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('document_expedition', models.CharField(blank=True, max_length=100, verbose_name='Lugar de expedición')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Celular/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contraparte', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Contraparte',
                'verbose_name_plural': 'Contrapartes',
            },
        ),
        migrations.CreateModel(
            name='InformacionEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos_salariales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos salariales')),
                ('ingresos_honorarios', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Honorarios')),
                ('ingresos_arrendamientos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Arrendamientos')),
                ('ingresos_pensiones', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pensiones')),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros ingresos')),
                ('descripcion_otros_ingresos', models.TextField(blank=True, verbose_name='Descripción otros ingresos')),
                ('gastos_alimentacion', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alimentación')),
                ('gastos_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Transporte')),
                ('gastos_servicios_publicos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Servicios públicos')),
                ('gastos_arriendo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Arriendo')),
                ('otros_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros egresos')),
                ('descripcion_otros_egresos', models.TextField(blank=True, verbose_name='Descripción otros egresos')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_economica', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Información Económica',
                'verbose_name_plural': 'Información Económica',
            },
        ),
        migrations.CreateModel(
            name='InformacionPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_casa', models.BooleanField(default=False, verbose_name='Tiene casa')),
                ('cantidad_casas', models.PositiveIntegerField(default=0, verbose_name='Cantidad de casas')),
                ('tiene_apartamento', models.BooleanField(default=False, verbose_name='Tiene apartamento')),
                ('cantidad_apartamentos', models.PositiveIntegerField(default=0, verbose_name='Cantidad de apartamentos')),
                ('tiene_local_comercial', models.BooleanField(default=False, verbose_name='Tiene local comercial')),
                ('cantidad_locales', models.PositiveIntegerField(default=0, verbose_name='Cantidad de locales')),
                ('tiene_vehiculo', models.BooleanField(default=False, verbose_name='Tiene vehículo')),
                ('cantidad_vehiculos', models.PositiveIntegerField(default=0, verbose_name='Cantidad de vehículos')),
                ('tiene_otros_activos', models.BooleanField(default=False, verbose_name='Tiene otros activos')),
                ('descripcion_otros_activos', models.TextField(blank=True, verbose_name='Descripción otros activos (CDT, Bonos, Acciones, Maquinaria, etc.)')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_patrimonial', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Información Patrimonial',
                'verbose_name_plural': 'Información Patrimonial',
            },
        ),
        migrations.CreateModel(
            name='RelacionHechos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_hechos', models.TextField(verbose_name='Descripción de los hechos')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_hechos', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Relación de Hechos',
                'verbose_name_plural': 'Relación de Hechos',
            },
        ),
        migrations.CreateModel(
            name='SolucionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion_propuesta', models.TextField(verbose_name='Posible solución al caso (debidamente sustentada)')),
                ('fecha_limite_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha límite entrega del documento')),
                ('susceptible_conciliacion', models.BooleanField(default=False, verbose_name='¿Es susceptible de conciliación?')),
                ('solicitud_conciliacion_diligenciada', models.BooleanField(default=False, verbose_name='¿Se diligencio solicitud de conciliación?')),
                ('intencion_usuario', models.CharField(blank=True, choices=[('conciliar', 'Conciliar u otro instrumento MASC'), ('procedibilidad', 'Cumplir requisito de procedibilidad'), ('dialogar', 'Dialogar con la ayuda de un tercero')], max_length=20, verbose_name='Intención del usuario')),
                ('email_autorizacion', models.EmailField(blank=True, max_length=254, verbose_name='Email autorizado para envío')),
                ('documentos_pendientes', models.TextField(blank=True, verbose_name='Relación de documentos e información pendiente')),
                ('fecha_limite_documentos', models.DateField(blank=True, null=True, verbose_name='Plazo máximo entrega documentos pendientes')),
                ('estudiante_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre completo del estudiante')),
                ('estudiante_codigo', models.CharField(blank=True, max_length=20, verbose_name='Código IDUNAB del estudiante')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solucion', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Solución del Caso',
                'verbose_name_plural': 'Soluciones de Casos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAsesorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombres y apellidos completos')),
                ('document_type', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso por Protección Temporal'), ('NIT', 'NIT'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('document_expedition', models.CharField(blank=True, max_length=100, verbose_name='Lugar de expedición')),
                ('address', models.TextField(verbose_name='Dirección domicilio')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Barrio')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Celular/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('housing_type', models.CharField(choices=[('propia_hipoteca', 'Propia con hipoteca'), ('propia_sin_hipoteca', 'Propia sin hipoteca'), ('familiar', 'Familiar'), ('arrendada', 'Arrendada'), ('habitacion', 'Habitación')], max_length=20, verbose_name='Tipo de vivienda')),
                ('workplace_address', models.TextField(blank=True, verbose_name='Dirección empresa/lugar de trabajo')),
                ('workplace_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono lugar de trabajo')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ocupación')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ingresos mensuales')),
                ('dependents_count', models.PositiveIntegerField(default=0, verbose_name='Número de personas a cargo')),
                ('civil_status', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Unión libre'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('separado', 'Separado/a')], max_length=15, verbose_name='Estado civil')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_asesorado', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Usuario Asesorado',
                'verbose_name_plural': 'Usuarios Asesorados',
            },
        ),
    ]
