# Generated by Django 5.0.8 on 2025-09-20 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexousuario',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='consultoriojuridico',
            name='assigned_teacher',
        ),
        migrations.RemoveField(
            model_name='consultoriojuridico',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='relacionhechos',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='contraparte',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='informacioneconomica',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='solucioncaso',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='informacionpatrimonial',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='usuarioasesorado',
            name='caso',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('estudiante', 'Estudiante'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('tipo_caso', models.CharField(blank=True, choices=[('civil', 'Civil'), ('penal', 'Penal'), ('laboral', 'Laboral'), ('administrativo', 'Administrativo'), ('comercial', 'Comercial'), ('familia', 'Familia')], max_length=20)),
                ('paso_actual', models.IntegerField(default=1)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('titulo_caso', models.CharField(blank=True, max_length=200)),
                ('descripcion_breve', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to=settings.AUTH_USER_MODEL)),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='casos_archivos/%Y/%m/%d/')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50)),
                ('tamaño_archivo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('paso_relacionado', models.IntegerField(blank=True, help_text='Paso del wizard al que pertenece', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='denuncias.caso')),
            ],
        ),
        migrations.CreateModel(
            name='DanosPerjuicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_dano', models.JSONField(default=list, help_text='Lista de tipos de daño')),
                ('descripcion_danos', models.TextField(help_text='Descripción detallada de los daños')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moneda', models.CharField(default='COP', max_length=10)),
                ('gastos_medicos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gastos_legales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('otros_gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descripcion_impacto', models.TextField(blank=True, help_text='Descripción del impacto en la vida')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='danos_perjuicios', to='denuncias.caso')),
            ],
        ),
        migrations.CreateModel(
            name='HechosCircunstancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hechos', models.DateField(help_text='Fecha en que ocurrieron los hechos')),
                ('lugar_hechos', models.CharField(help_text='Lugar donde ocurrieron los hechos', max_length=200)),
                ('descripcion_hechos', models.TextField(help_text='Descripción detallada de los hechos')),
                ('circunstancias', models.TextField(blank=True, help_text='Circunstancias adicionales relevantes')),
                ('testigos_presentes', models.BooleanField(default=False)),
                ('autoridades_intervinieron', models.BooleanField(default=False)),
                ('descripcion_autoridades', models.TextField(blank=True)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hechos_circunstancias', to='denuncias.caso')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_legales', models.TextField(blank=True, help_text='Antecedentes legales relacionados')),
                ('procesos_anteriores', models.BooleanField(default=False)),
                ('descripcion_procesos', models.TextField(blank=True)),
                ('urgencia_caso', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('plazo_respuesta', models.CharField(blank=True, help_text='Plazo esperado de respuesta', max_length=100)),
                ('observaciones_adicionales', models.TextField(blank=True)),
                ('comentarios_especiales', models.TextField(blank=True)),
                ('autorizacion_tratamiento_datos', models.BooleanField(default=False)),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_adicional', to='denuncias.caso')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionDemandado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('razon_social', models.CharField(blank=True, help_text='Si es empresa', max_length=200)),
                ('numero_identificacion', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('es_empresa', models.BooleanField(default=False)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_demandado', to='denuncias.caso')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula de Ciudadanía'), ('cedula_extranjeria', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte'), ('tarjeta_identidad', 'Tarjeta de Identidad')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Unión Libre'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20)),
                ('profesion', models.CharField(blank=True, max_length=100)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_personal', to='denuncias.caso')),
            ],
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='denuncias.caso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pretensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretension_principal', models.TextField(help_text='Pretensión principal que se solicita')),
                ('pretensiones_subsidiarias', models.TextField(blank=True, help_text='Pretensiones subsidiarias')),
                ('solicita_indemnizacion', models.BooleanField(default=False)),
                ('valor_indemnizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('solicita_medidas_cautelares', models.BooleanField(default=False)),
                ('descripcion_medidas', models.TextField(blank=True)),
                ('otras_solicitudes', models.TextField(blank=True, help_text='Otras solicitudes específicas')),
                ('fundamentos_derecho', models.TextField(blank=True, help_text='Fundamentos de derecho aplicables')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretensiones', to='denuncias.caso')),
            ],
        ),
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_prueba', models.JSONField(default=list)),
                ('descripcion_pruebas', models.TextField(help_text='Descripción de las pruebas disponibles')),
                ('tiene_documentos', models.BooleanField(default=False)),
                ('lista_documentos', models.TextField(blank=True, help_text='Lista de documentos disponibles')),
                ('tiene_testigos', models.BooleanField(default=False)),
                ('requiere_pericias', models.BooleanField(default=False)),
                ('descripcion_pericias', models.TextField(blank=True)),
                ('ubicacion_pruebas', models.TextField(blank=True, help_text='Dónde se encuentran las pruebas')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='denuncias.caso')),
            ],
        ),
        migrations.CreateModel(
            name='Testigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('relacion_caso', models.CharField(help_text='Relación con el caso', max_length=100)),
                ('que_presencio', models.TextField(help_text='Qué presenció o conoce del caso')),
                ('disponible_testificar', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testigos', to='denuncias.caso')),
            ],
        ),
        migrations.DeleteModel(
            name='ActividadEconomica',
        ),
        migrations.DeleteModel(
            name='AnexoUsuario',
        ),
        migrations.DeleteModel(
            name='RelacionHechos',
        ),
        migrations.DeleteModel(
            name='Contraparte',
        ),
        migrations.DeleteModel(
            name='InformacionEconomica',
        ),
        migrations.DeleteModel(
            name='SolucionCaso',
        ),
        migrations.DeleteModel(
            name='InformacionPatrimonial',
        ),
        migrations.DeleteModel(
            name='ConsultorioJuridico',
        ),
        migrations.DeleteModel(
            name='UsuarioAsesorado',
        ),
    ]
