# Generated by Django 5.0.8 on 2025-09-20 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_remove_anexousuario_caso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danosperjuicios',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='hechoscircunstancias',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='informacionadicional',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='informaciondemandado',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='informacionpersonal',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='logactividad',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='logactividad',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pretensiones',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='pruebas',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='testigos',
            name='caso',
        ),
        migrations.AlterModelOptions(
            name='caso',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Caso', 'verbose_name_plural': 'Casos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso por Protección Temporal'), ('NIT', 'NIT'), ('OTRO', 'Otro')], default='CC', max_length=10, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='descripcion_breve',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='caso',
            name='tipo_caso',
            field=models.CharField(choices=[('civil', 'Civil'), ('penal', 'Penal'), ('laboral', 'Laboral'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='caso',
            name='titulo_caso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='caso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_denuncia_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caso',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_denuncia_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador/Docente'), ('estudiante', 'Estudiante'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='caso',
            table='denuncias_caso',
        ),
        migrations.AlterModelTable(
            name='user',
            table='denuncias_user',
        ),
        migrations.CreateModel(
            name='ConsultorioJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nua', models.CharField(max_length=20, unique=True, verbose_name='Número Único de Asesoría (NUA)')),
                ('consultation_date', models.DateField(verbose_name='Fecha de asesoría')),
                ('consultation_area', models.CharField(choices=[('civil', 'Civil'), ('publico', 'Público'), ('laboral', 'Laboral'), ('penal', 'Penal'), ('comercial', 'Comercial'), ('familia', 'Familia'), ('otro', 'Otro')], max_length=20, verbose_name='Área de consulta')),
                ('consultation_area_other', models.CharField(blank=True, max_length=100, verbose_name='Otra área (especificar)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de revisión'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultorio_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Docente asignado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultorio_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Caso Consultorio Jurídico',
                'verbose_name_plural': 'Casos Consultorio Jurídico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnexoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anexo', models.CharField(max_length=200, verbose_name='Nombre del anexo')),
                ('archivo', models.FileField(upload_to='anexos/%Y/%m/', verbose_name='Archivo')),
                ('numero_folios', models.PositiveIntegerField(default=1, verbose_name='Número de folios')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Anexo Usuario',
                'verbose_name_plural': 'Anexos Usuario',
            },
        ),
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('empleado', 'Empleado/a'), ('pensionado', 'Pensionado/a'), ('independiente', 'Independiente')], max_length=15, verbose_name='Tipo de actividad')),
                ('employer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del empleador')),
                ('pension_fund', models.CharField(blank=True, max_length=100, verbose_name='Fondo de pensión')),
                ('independent_activity', models.TextField(blank=True, verbose_name='Tipo de actividad independiente')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_economica', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Actividad Económica',
                'verbose_name_plural': 'Actividades Económicas',
            },
        ),
        migrations.CreateModel(
            name='Contraparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombres y apellidos/Denominación')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso por Protección Temporal'), ('NIT', 'NIT'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('document_expedition', models.CharField(blank=True, max_length=100, verbose_name='Lugar de expedición')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Celular/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contraparte', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Contraparte',
                'verbose_name_plural': 'Contrapartes',
            },
        ),
        migrations.CreateModel(
            name='InformacionEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos_salariales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos salariales')),
                ('ingresos_honorarios', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Honorarios')),
                ('ingresos_arrendamientos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Arrendamientos')),
                ('ingresos_pensiones', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pensiones')),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros ingresos')),
                ('descripcion_otros_ingresos', models.TextField(blank=True, verbose_name='Descripción otros ingresos')),
                ('gastos_alimentacion', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alimentación')),
                ('gastos_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Transporte')),
                ('gastos_servicios_publicos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Servicios públicos')),
                ('gastos_arriendo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Arriendo')),
                ('otros_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros egresos')),
                ('descripcion_otros_egresos', models.TextField(blank=True, verbose_name='Descripción otros egresos')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_economica', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Información Económica',
                'verbose_name_plural': 'Información Económica',
            },
        ),
        migrations.CreateModel(
            name='InformacionPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_casa', models.BooleanField(default=False, verbose_name='Tiene casa')),
                ('cantidad_casas', models.PositiveIntegerField(default=0, verbose_name='Cantidad de casas')),
                ('tiene_apartamento', models.BooleanField(default=False, verbose_name='Tiene apartamento')),
                ('cantidad_apartamentos', models.PositiveIntegerField(default=0, verbose_name='Cantidad de apartamentos')),
                ('tiene_local_comercial', models.BooleanField(default=False, verbose_name='Tiene local comercial')),
                ('cantidad_locales', models.PositiveIntegerField(default=0, verbose_name='Cantidad de locales')),
                ('tiene_vehiculo', models.BooleanField(default=False, verbose_name='Tiene vehículo')),
                ('cantidad_vehiculos', models.PositiveIntegerField(default=0, verbose_name='Cantidad de vehículos')),
                ('tiene_otros_activos', models.BooleanField(default=False, verbose_name='Tiene otros activos')),
                ('descripcion_otros_activos', models.TextField(blank=True, verbose_name='Descripción otros activos')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_patrimonial', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Información Patrimonial',
                'verbose_name_plural': 'Información Patrimonial',
            },
        ),
        migrations.CreateModel(
            name='RelacionHechos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_hechos', models.TextField(verbose_name='Descripción de los hechos')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_hechos', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Relación de Hechos',
                'verbose_name_plural': 'Relación de Hechos',
            },
        ),
        migrations.CreateModel(
            name='SolucionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion_propuesta', models.TextField(verbose_name='Posible solución al caso (debidamente sustentada)')),
                ('fecha_limite_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha límite entrega del documento')),
                ('susceptible_conciliacion', models.BooleanField(default=False, verbose_name='¿Es susceptible de conciliación?')),
                ('solicitud_conciliacion_diligenciada', models.BooleanField(default=False, verbose_name='¿Se diligenció solicitud de conciliación?')),
                ('intencion_usuario', models.CharField(blank=True, choices=[('conciliar', 'Conciliar u otro instrumento MASC'), ('procedibilidad', 'Cumplir requisito de procedibilidad'), ('dialogar', 'Dialogar con la ayuda de un tercero')], max_length=20, verbose_name='Intención del usuario')),
                ('email_autorizacion', models.EmailField(blank=True, max_length=254, verbose_name='Email autorizado para envío')),
                ('documentos_pendientes', models.TextField(blank=True, verbose_name='Relación de documentos e información pendiente')),
                ('fecha_limite_documentos', models.DateField(blank=True, null=True, verbose_name='Plazo máximo entrega documentos pendientes')),
                ('estudiante_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre completo del estudiante')),
                ('estudiante_codigo', models.CharField(blank=True, max_length=20, verbose_name='Código IDUNAB del estudiante')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solucion', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Solución del Caso',
                'verbose_name_plural': 'Soluciones de Casos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAsesorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombres y apellidos completos')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso por Protección Temporal'), ('NIT', 'NIT'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('document_expedition', models.CharField(blank=True, max_length=100, verbose_name='Lugar de expedición')),
                ('address', models.TextField(verbose_name='Dirección domicilio')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Barrio')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Celular/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('housing_type', models.CharField(choices=[('propia_hipoteca', 'Propia con hipoteca'), ('propia_sin_hipoteca', 'Propia sin hipoteca'), ('familiar', 'Familiar'), ('arrendada', 'Arrendada'), ('habitacion', 'Habitación')], max_length=20, verbose_name='Tipo de vivienda')),
                ('workplace_address', models.TextField(blank=True, verbose_name='Dirección empresa/lugar de trabajo')),
                ('workplace_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono lugar de trabajo')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ocupación')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ingresos mensuales')),
                ('dependents_count', models.PositiveIntegerField(default=0, verbose_name='Número de personas a cargo')),
                ('civil_status', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Unión libre'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('separado', 'Separado/a')], max_length=15, verbose_name='Estado civil')),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_asesorado', to='denuncias.consultoriojuridico', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Usuario Asesorado',
                'verbose_name_plural': 'Usuarios Asesorados',
            },
        ),
        migrations.DeleteModel(
            name='ArchivoCaso',
        ),
        migrations.DeleteModel(
            name='DanosPerjuicios',
        ),
        migrations.DeleteModel(
            name='HechosCircunstancias',
        ),
        migrations.DeleteModel(
            name='InformacionAdicional',
        ),
        migrations.DeleteModel(
            name='InformacionDemandado',
        ),
        migrations.DeleteModel(
            name='InformacionPersonal',
        ),
        migrations.DeleteModel(
            name='LogActividad',
        ),
        migrations.DeleteModel(
            name='Pretensiones',
        ),
        migrations.DeleteModel(
            name='Pruebas',
        ),
        migrations.DeleteModel(
            name='Testigos',
        ),
    ]
