# Generated by Django 5.0.8 on 2025-09-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_remove_danosperjuicios_caso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contraparte',
        ),
    ]
