# Generated by Django 5.0.8 on 2025-09-27 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_delete_contraparte'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('paso1', 'Información Personal'), ('paso2', 'Actividad Económica'), ('paso3', 'Información Patrimonial'), ('paso4', 'Información Económica'), ('paso6', 'Relación de Hechos'), ('paso7', 'Anexos'), ('paso8', 'Solución del Caso'), ('general', 'Comentario General')], help_text='Sección del formulario sobre la que se comenta', max_length=20)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('revision', 'Necesita Revisión'), ('rechazado', 'Rechazado'), ('info', 'Información')], help_text='Estado de aprobación de la sección', max_length=20)),
                ('comentario', models.TextField(help_text='Comentario detallado del docente')),
                ('es_critico', models.BooleanField(default=False, help_text='Si requiere corrección obligatoria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leido_por_estudiante', models.BooleanField(default=False)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='denuncias.consultoriojuridico')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_dado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback de Docente',
                'verbose_name_plural': 'Feedback de Docentes',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('caso', 'docente', 'seccion')},
            },
        ),
    ]
