# Generated by Django 5.0.8 on 2025-09-27 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_feedbackdocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultoriojuridico',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultorio_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Docente asignado'),
        ),
        migrations.AlterField(
            model_name='consultoriojuridico',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('pending_review', 'Pendiente de revisión'), ('in_review', 'En revisión'), ('reviewed', 'Revisado'), ('rejected', 'Rechazado'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
