# Generated by Django 5.0.8 on 2025-10-03 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0006_alter_consultoriojuridico_assigned_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_modificacion', models.CharField(choices=[('creacion', 'Creación del caso'), ('edicion', 'Edición de datos'), ('cambio_estado', 'Cambio de estado'), ('feedback', 'Feedback docente'), ('asignacion', 'Asignación de docente'), ('finalizacion', 'Finalización del caso')], max_length=20)),
                ('seccion_modificada', models.CharField(blank=True, help_text='Qué sección fue modificada (paso1, paso2, etc.)', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción detallada del cambio')),
                ('estado_anterior', models.CharField(blank=True, help_text='Estado anterior del caso (si aplica)', max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, help_text='Nuevo estado del caso (si aplica)', max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_transcurrido', models.DurationField(blank=True, help_text='Tiempo desde la última modificación', null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='denuncias.consultoriojuridico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Modificación',
                'verbose_name_plural': 'Historial de Modificaciones',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['caso', '-fecha_modificacion'], name='denuncias_h_caso_id_3721c2_idx'), models.Index(fields=['usuario', '-fecha_modificacion'], name='denuncias_h_usuario_69de02_idx')],
            },
        ),
    ]
